version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: dc-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-dcpassword123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dc_management}
      MYSQL_USER: ${MYSQL_USER:-dcuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dcpass123}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dc-network

  backend:
    build: ./backend
    container_name: dc-backend
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE:-dc_management}
      DB_USER: ${MYSQL_USER:-dcuser}
      DB_PASSWORD: ${MYSQL_PASSWORD:-dcpass123}
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-key}
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dc-network

  frontend:
    build: ./frontend
    container_name: dc-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - dc-network

  prometheus:
    image: prom/prometheus:latest
    container_name: dc-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - dc-network

  grafana:
    image: grafana/grafana:latest
    container_name: dc-grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin123}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - dc-network

volumes:
  mysql_data:
  prometheus_data:
  grafana_data:

networks:
  dc-network:
    driver: bridge